import {
  amberDark,
  blueDark,
  bronzeDark,
  brownDark,
  crimsonDark,
  cyanDark,
  goldDark,
  grassDark,
  grayDark,
  indigoDark,
  limeDark,
  mauveDark,
  mintDark,
  oliveDark,
  orangeDark,
  pinkDark,
  plumDark,
  purpleDark,
  redDark,
  sageDark,
  sandDark,
  skyDark,
  slateDark,
  tealDark,
  tomatoDark,
  violetDark,
  yellowDark,
} from '@radix-ui/colors';

export const dark = {
  ...grayDark,
  ...mauveDark,
  ...slateDark,
  ...sageDark,
  ...oliveDark,
  ...sandDark,
  ...tomatoDark,
  ...redDark,
  ...crimsonDark,
  ...pinkDark,
  ...plumDark,
  ...purpleDark,
  ...violetDark,
  ...indigoDark,
  ...blueDark,
  ...cyanDark,
  ...tealDark,
  ...grassDark,
  ...brownDark,
  ...orangeDark,
  ...skyDark,
  ...mintDark,
  ...limeDark,
  ...yellowDark,
  ...amberDark,
  ...goldDark,
  ...bronzeDark,
};

export const darkGroups = [
  ...new Set(Object.keys(dark).map((key) => key.replace(/[0-9]/g, ''))),
];
